### ISSUE TITLE
LICENSE.txt detritus?

### ISSUE THREAD

**Issue by jhgit** [include-what-you-use/include-what-you-use.org#1]
Can the "Copyrights and Licenses for Third Party Software Distributed with LLVM" section of LICENSE.txt be removed? Looks like it's copy/paste baggage and doesn't apply to iwyu.

**Comment by kimgr** [comment]
Thanks, see new pull request https://github.com/include-what-you-use/include-what-you-use/issues/236. This issue should probably have gone in the include-what-you-use project, but we can figure it out here.

**Comment by vsapsai** [comment]
As the reported issue is fixed, closing it.
